### ISSUE TITLE
ppc64-diag rtas_errd prevents booting Firestone

### ISSUE THREAD

**Issue by sgarfinkle** [open-power-host-os/ppc64-diag#1]
On my p8 firestone system, a hostos update has made the system unbootable. During boot I get
  [FAILED] Failed to start ppc64-diag rtas_errd (platform error handling) Service. See 'systemctl status rtas_errd.service' for details.

I have no idea how to get to that log since it's so early in the boot that I can't get a shell. This seems to have happened after a recent BMC firmware update. Anyway, I reinstalled Centos 7.4 from scratch with no problem. Once I added the hostos repo and did a yum udpate (pulling in the hostos packages), the system can no longer boot. 

<cde:info> Mirrored with LTC bug #159509 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2017-10-03 13:40:54 EDT-------
This P8 system is now unsable to me because of what seems either to be a regression in rtas _errd or a change in the firmware that causes rtas_errd to choke.

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-10-03 13:51:25 EDT-------
(In reply to comment #4)
&gt; This P8 system is now unsable to me because of what seems either to be a
&gt; regression in rtas _errd or a change in the firmware that causes rtas_errd
&gt; to choke.

There was a regression in ppc64-diag package (Accidentally it tried to start rtas_errd daemon on PowerNV host). This is already fixed and pushed to hostos ppc64-diag repository (both devel and release branch).

I don't think it will stop system from booting. You may see log of rtas_errd start/failed messages in syslog as it repeatedly tries to restart the daemon. 

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-10-03 14:27:01 EDT-------
Looks like build team didn't pick up ppc64-diag changes. Can you please pick latest changes ? 

I've entered runlevel 1 and modified service script for now. But its unrelated to system hang! that's different.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From muriloo@br.ibm.com 2017-10-03 14:57:02 EDT-------
(In reply to comment #6)
&gt; Looks like build team didn't pick up ppc64-diag changes. Can you please pick
&gt; latest changes ? 

Hi, Vasant.

Can you please be more specific as to latest changes? What's the commit ID missing on Devel or Release builds?

As of this writing, the latest commits from
hostos-devel (608507ea8ed81209204feacbbde40e234d261141)
and
hostos-release (608507ea8ed81209204feacbbde40e234d261141)
branches are built and available at
http://pokgsa.ibm.com/projects/h/host-os/devel/2017-10-01/repository/ppc64-diag/ and
http://pokgsa.ibm.com/projects/h/host-os/release/2017-09-29/repository/ppc64-diag/, respectively.

**Comment by olavph** [comment]
Please note that the version tagged as release do not contain the latest ppc64-diag commit (608507ea8ed81209204feacbbde40e234d261141) from the hostos-release branch (https://github.com/open-power-host-os/versions/blob/3.0-2017-09-22/ppc64-diag/ppc64-diag.yaml).
The latest repository, pointed by @mopsfelder, should contain it, though.

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-10-04 00:02:09 EDT-------
(In reply to comment #7)
&gt; (In reply to comment #6)
&gt; &gt; Looks like build team didn't pick up ppc64-diag changes. Can you please pick
&gt; &gt; latest changes ? 
&gt; 
&gt; Hi, Vasant.
&gt; 
&gt; Can you please be more specific as to latest changes? What's the commit ID
&gt; missing on Devel or Release builds?
&gt; 
&gt; As of this writing, the latest commits from
&gt; hostos-devel (608507ea8ed81209204feacbbde40e234d261141)

Yes.. top commit (commit 608507ea) is a regression fix. If you have already built with this then fine.

But kofr2.aus.stglabs.ibm.com was not having this fix. Hence I mentioned we need above fix.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2017-10-31 15:45:40 EDT-------
Issue went away after reinstalling.
